import { createFileRoute } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CalendarClock, ListChecks, Loader2, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  BulletList,
  CopyButton,
  ErrorNotice,
  LoadingPanel,
  PageHeader,
  ResultSection,
  errorMessage,
} from "@/components/ai-ui";
import { planTasks } from "@/lib/ai.functions";

export const Route = createFileRoute("/tasks")({
  head: () => ({
    meta: [
      { title: "AI Task Planner — WorkFlow AI" },
      {
        name: "description",
        content:
          "Add tasks with deadlines and priorities, then let AI rank them and build a realistic schedule.",
      },
      { property: "og:title", content: "AI Task Planner — WorkFlow AI" },
      {
        property: "og:description",
        content: "Prioritized task order and a realistic daily schedule, generated by AI.",
      },
    ],
  }),
  component: TasksPage,
});

type Task = { id: string; name: string; deadline: string; priority: string };

const priorityTone: Record<string, string> = {
  High: "border-destructive/40 bg-destructive/10 text-destructive",
  Medium: "border-warning/40 bg-warning/15 text-warning-foreground",
  Low: "border-success/40 bg-success/10 text-success",
};

function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [name, setName] = useState("");
  const [deadline, setDeadline] = useState("");
  const [priority, setPriority] = useState("Medium");

  const run = useServerFn(planTasks);
  const mutation = useMutation({
    mutationFn: (list: Task[]) =>
      run({
        data: {
          tasks: list.map(({ name: n, deadline: d, priority: p }) => ({
            name: n,
            deadline: d,
            priority: p,
          })),
        },
      }),
  });
  const plan = mutation.data;

  return (
    <div className="mx-auto max-w-5xl">
      <PageHeader
        eyebrow="Planning"
        title="AI Task Planner"
        description="Capture what's on your plate. WorkFlow AI ranks the work, explains the order and builds a realistic schedule."
      />

      <div className="grid gap-6 lg:grid-cols-[1fr_1.1fr]">
        <div className="space-y-4">
          <form
            className="surface-card space-y-4 p-6"
            onSubmit={(e) => {
              e.preventDefault();
              if (!name.trim()) return;
              setTasks((t) => [
                ...t,
                { id: crypto.randomUUID(), name: name.trim(), deadline, priority },
              ]);
              setName("");
              setDeadline("");
              setPriority("Medium");
            }}
          >
            <div className="space-y-2">
              <Label htmlFor="task">Task name</Label>
              <Input
                id="task"
                placeholder="Finalise the client proposal"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="deadline">Deadline</Label>
                <Input
                  id="deadline"
                  type="date"
                  value={deadline}
                  onChange={(e) => setDeadline(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="priority">Priority</Label>
                <Select value={priority} onValueChange={setPriority}>
                  <SelectTrigger id="priority">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="High">High</SelectItem>
                    <SelectItem value="Medium">Medium</SelectItem>
                    <SelectItem value="Low">Low</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <Button type="submit" variant="secondary" className="w-full" disabled={!name.trim()}>
              <Plus className="h-4 w-4" />
              Add task
            </Button>
          </form>

          <section className="surface-card p-5">
            <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
              Your tasks ({tasks.length})
            </h3>
            {tasks.length === 0 ? (
              <p className="text-sm text-muted-foreground">No tasks yet. Add your first one.</p>
            ) : (
              <ul className="space-y-2">
                {tasks.map((task) => (
                  <li
                    key={task.id}
                    className="flex items-center justify-between gap-3 rounded-lg border border-border bg-secondary/50 px-3 py-2"
                  >
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{task.name}</p>
                      <p className="text-xs text-muted-foreground">
                        {task.deadline ? `Due ${task.deadline}` : "No deadline"}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className={priorityTone[task.priority]}>
                        {task.priority}
                      </Badge>
                      <button
                        type="button"
                        aria-label={`Remove ${task.name}`}
                        onClick={() => setTasks((t) => t.filter((x) => x.id !== task.id))}
                        className="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  </li>
                ))}
              </ul>
            )}
            <Button
              className="mt-4 w-full"
              disabled={tasks.length === 0 || mutation.isPending}
              onClick={() => mutation.mutate(tasks)}
            >
              {mutation.isPending ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <ListChecks className="h-4 w-4" />
              )}
              {mutation.isPending ? "Planning…" : "Prioritize & schedule"}
            </Button>
          </section>
        </div>

        <div className="space-y-4">
          {mutation.isError && <ErrorNotice message={errorMessage(mutation.error)} />}
          {mutation.isPending && <LoadingPanel message="Building your schedule…" />}
          {plan && !mutation.isPending && (
            <>
              <ResultSection
                title="Recommended order"
                action={
                  <CopyButton
                    value={plan.order.map((o, i) => `${i + 1}. ${o.task} — ${o.reason}`).join("\n")}
                    label="Copy order"
                  />
                }
              >
                <ol className="space-y-3">
                  {plan.order.map((item, i) => (
                    <li key={i} className="flex gap-3">
                      <span className="brand-gradient flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold text-primary-foreground">
                        {i + 1}
                      </span>
                      <div>
                        <p className="text-sm font-medium">{item.task}</p>
                        <p className="text-xs text-muted-foreground">{item.reason}</p>
                      </div>
                    </li>
                  ))}
                </ol>
              </ResultSection>

              <ResultSection title="Suggested schedule">
                <div className="space-y-4">
                  {plan.schedule.map((block, i) => (
                    <div key={i}>
                      <p className="flex items-center gap-2 text-sm font-medium">
                        <CalendarClock className="h-4 w-4 text-accent" />
                        {block.period}
                      </p>
                      <div className="mt-2 pl-6">
                        <BulletList items={block.items} empty="Nothing scheduled." />
                      </div>
                    </div>
                  ))}
                </div>
              </ResultSection>

              {plan.advice && (
                <ResultSection title="Coach's note">
                  <p className="text-sm leading-relaxed">{plan.advice}</p>
                </ResultSection>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
